### ISSUE TITLE
Need a regex filter

### ISSUE THREAD

**Issue by greed2411** [Jaiimmortal/WFC#1]
Need a regex filter or an ordinary word-filter to remove all the SPL characters out of the words in a list.

Example words_list = [ '"hello' , 'this:' , 'i7' ]
 which should turn into clean_list = [ 'hello' , 'this' , 'i7' ]

**Comment by bhaveshpraveen** [comment]
Your repo is private. Make it public

**Comment by bhaveshpraveen** [comment]
def func(i):
  return re.sub('[,./<>?;\':"\[\]{}|`~\-_=+)(*&^%$#@!]', '', i)
words_list = [ '"hell/o' , 'this:' , 'i7' ]
words_list = list(map(func, words_list))

**Comment by bhaveshpraveen** [comment]
def func(i):
    return re.sub('[,./<>?;\':"\[\]{}|`~\-_=+)(*&^%$#@!]', '', i)
words_list = [ '"hell/o' , 'this:' , 'i7' ]
words_list = list(map(func, words_list))

**Comment by bhaveshpraveen** [comment]
just indent the return statement

**Comment by bhaveshpraveen** [comment]
def func(i):
  return re.sub('[,./<>?;\':"\[\]{}|`~\-_=+)(*&^%$#@!]', '', i)
words_list = [ '"he$ll/o' , 'this:' , 'i7' ]
words_list = list(map(func, words_list))

**Comment by bhaveshpraveen** [comment]
https://gist.github.com/bhaveshpraveen/941b434ea3ca3679aab0bd6530d300c6

**Comment by greed2411** [comment]
Thanks, @bhaveshpraveen I saw the comment half hour ago, didn't know why I didn't get any notification.
Thanks, @MINOSai as well.
